<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">安规电容</h1>
      <ol class="breadcrumb">
        <li><a href="/">主页</a></li>
        <li>产品展示</li>
        <li class="active">安规电容</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <!-- Products -->
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/capacitor/mkp_x2.jpg" alt="" />
        <div class="caption">
          <h3>MKP-X2</h3>
          <p>阻容降压专用交流安规电容</p>
          <p>高耐压、耐湿热、低容降，专用于阻容降压电路</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/capacitor/cbb21.jpg" alt="" />
        <div class="caption">
          <h3>CBB20/21/22/81</h3>
          <p>金属化聚丙烯薄膜电容</p>
          <p>采用金属化聚丙烯薄膜无感式卷绕、采用阻燃环氧粉末包封、阻燃环氧粉末包封、具有防潮能力强、自愈性好、高绝缘、低损耗、低温升等特点。</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/capacitor/cbb61.jpg" alt="" />
        <div class="caption">
          <h3>CBB61</h3>
          <p>CB B 6 1调速系列</p>
          <p>专为风扇调速器而设计，多芯组合式结构，可实现2~4芯模块式封装。多种个性化安装结构可选，采用特殊制造工艺，电性能稳定。</p>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <?php $this->display('copyright.phtml'); ?>
</div>
<!-- /.container -->
<?php $this->display('footer.phtml'); ?>