<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">保险丝</h1>
      <ol class="breadcrumb">
        <li><a href="/">主页</a></li>
        <li>产品展示</li>
        <li class="active">保险丝</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <!-- Products -->
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/fuse/conquer_ceramic_glass.jpg" alt="" />
        <div class="caption">
          <h3>引线式玻璃管与陶瓷管保险丝</h3>
          <p>传统型管状产品，由金属熔体加管状外壳组产品规格非常丰富：对热冲击和机械冲击有很强的承受能力</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/fuse/conquer_micro.jpg" alt="" />
        <div class="caption">
          <h3>轴向引线式微小型保险丝</h3>
          <p>高突波承受能力对热冲击和机械冲击有很强的承受能力，高可靠性和稳定的焊锡性</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/fuse/aem_af2.jpg" alt="" />
        <div class="caption">
          <h3>薄膜晶片保险丝</h3>
          <p>特殊的多膜层结构使熔断特性稳定，高防爆性与表面耐刮特性，适用于含铅与无铅之回焊炉和波焊制程。</p>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <?php $this->display('copyright.phtml'); ?>
</div>
<!-- /.container -->
<?php $this->display('footer.phtml'); ?>