<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">压敏电阻</h1>
      <ol class="breadcrumb">
        <li><a href="/">主页</a></li>
        <li>产品展示</li>
        <li class="active">压敏电阻</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <!-- Products -->
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/varistor/jyr.jpg" alt="" />
        <div class="caption">
          <h3>HVR系列(Series)</h3>
          <p>HVR型氧化锌压敏电阻(HVR Series)</p>
          <p>耐脉冲电流大、体积小、适合PCB安装5D~20D 18V~1800V</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail"> <img src="/img/product/varistor/jyr.jpg" alt="" />
        <div class="caption">
          <h3>HVR芯片系列(Series)</h3>
          <p>HVR型氧化锌压敏电阻芯片(HVR Series)</p>
          <p>浪涌耐受能力高、体积小、安装方便5D~20D 18V~1800V</p>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
  <?php $this->display('copyright.phtml'); ?>
</div>
<!-- /.container -->
<?php $this->display('footer.phtml'); ?>