<hr />
<!-- Call to Action Section -->
<div class="well">
  <div class="row">
    <div class="col-md-8">
      <p>上海皓厚电子科技有限公司</p>
      <p>Shanghai HaoHou Electronic Technology Co.,Ltd</p>
      <p>上海市徐汇区漕溪路251弄望族城3号楼2005室, 200235</p>
      <p></p>
    </div>
    <div class="col-md-4">
      <a class="btn btn-lg btn-default btn-block" href="tel:02164282728"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (+86) 021 - 6428 2728</a>
      <a class="btn btn-lg btn-default btn-block" href="mailto:jackzhu@hhcsh.com.cn"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> jackzhu@hhcsh.com.cn</a>
    </div>
  </div>
</div>
<hr />
<!-- Footer -->
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p class="text-center">Copyright &copy; hhcsh.com.cn 2015</p>
    </div>
  </div>
</footer>
<!-- jQuery -->
<script src="<?=CDN_JQUERY;?>jquery-1.11.2.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<?=CDN_BOOTSTRAP;?>js/bootstrap.min.js"></script>