<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>上海皓厚电子科技有限公司</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?=CDN_BOOTSTRAP;?>css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="<?=CDN_BOOTSTRAP;?>css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <style type="text/css">
    body { padding-top: 70px; }
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img alt="Brand" src="/img/logo.gif" /></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li<?=($request->getControllerName() == 'About' ? ' class="active"' : '');?>> <a href="/about">公司简介</a> </li>
            <li class="dropdown<?=($request->getControllerName() == 'Product' ? ' active' : '');?>"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">产品展示 <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li> <a href="/product/hhc">皓华陶瓷电容</a> </li>
                <li> <a href="/product/mlcc">MLCC多层陶瓷电容</a> </li>
                <li> <a href="/product/fuse">保险丝</a> </li>
                <li> <a href="/product/varistor">压敏电阻</a> </li>
                <li> <a href="/product/capacitor">安规电容</a> </li>
              </ul>
            </li>
            <li<?=($request->getControllerName() == 'Contact' ? ' class="active"' : '');?>> <a href="/contact">联系我们</a> </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>