<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">欢迎光临上海皓厚电子科技有限公司</h2>
    </div>
    <div class="col-xs-12 col-sm-7">
      <p><strong>我们的宗旨</strong>：永远为顾客着想 </p>
      <p><strong>我们的使命</strong>：我们承诺提供高品位的产品。优质的服务和合理的价格，给顾客创造财富。</p>
      <p><strong>我们的战略</strong>：在电子元器件领域中，以产品质量为生命线，不断做大、做强，走可持续发展的道路，迅速成长为国际电子元器件领域中优秀的一员。</p>
      <p><strong>我们的理念</strong>：创造货真价实的产品与服务！</p>
      <p>　　　　　　创造得之有道的信誉和财富！</p>
      <p>　　　　　　创造务实清新的精神及文化！</p>
      <p><strong>我们的管理</strong>：采用高效的全程数字化管理，建立完善的规章制度，做到责任到人，有章必依，违章必究。</p>
      <p>主营产品有：</p>
      <ul>
        <li> <a href="/product/hhc">皓华陶瓷电容</a> </li>
        <li> <a href="/product/mlcc">MLCC多层陶瓷电容</a> </li>
        <li> <a href="/product/fuse">保险丝</a> </li>
        <li> <a href="/product/varistor">压敏电阻</a> </li>
        <li> <a href="/product/capacitor">安规电容</a> </li>
      </ul>
    </div>
    <div class="hidden-xs col-sm-5"> <img class="img-responsive" src="/img/ic.jpg" alt="" /></div>
  </div>
  <!-- /.row -->
  <!-- Products -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">销售品牌</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/aem.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/americanbrightled.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/avx.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/bm.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/bussmann.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/conquer.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/everlight.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/hec.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/hirose.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/holystone.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/jovin.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/kyocera.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/littelfuse.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/nichicon.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/panasonic.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/samsung.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/t-yuden.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/yageo.gif" alt="" /> </div>
  </div>
  <!-- Our Customers -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">主要合作伙伴</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/benq.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/chiffo.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/emerson_network_power.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/osram.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/primax.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/sanyo.gif" alt="" /> </div>
  </div>
  <!-- /.row -->
  <?php $this->display('copyright.phtml'); ?>
</div>
<!-- /.container -->
<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
	interval: 5000 //changes the speed
})
</script>
<?php $this->display('footer.phtml'); ?>